### PR TITLE
Update CI & general config

### PR DESCRIPTION
**Pull request by necaris**
A general cleanup since being moved over from github.com/upsidetravel , including:
 - replacing CircleCI with GitHub Actions
 - updating the PR template
 - removing the Upside CODEOWNERS file

We also need to disconnect the Upside CircleCI and CLA checks from PRs on this repo, but I think that'll require @syrusakbary or someone else with admin rights. Alternatively, if @dantheman39 and / or myself could get admin rights on this repo that would work too.

### CODE REVIEW

**Comment by syrusakbary** [comment]
I just removed the CircleCI webhook and CLA check :)

**Comment by necaris** [comment]
Can I get a review on this? @dantheman39 @syrusakbary

**Comment by dantheman39** [comment]
@necaris I approved but apparently no longer have write access.

**Comment by necaris** [comment]
@dantheman39 oops! Looks like I failed to follow up and ensure you had write access -- you should now, could you re-review?

**Pull request merged**
