### PR TITLE
Updates for 0.3.0

### PR DESCRIPTION
**Pull request by necaris**
Fixes for:
 - linting issues
 - type checking
 - Poetry (and other) dependencies
 - expanding test coverage to more recent Pythons, and dropping 3.6
 - support for more recent Pydantic, and dropping older versions

### CODE REVIEW

**Review by dantheman39 — APPROVED** [review]
Thanks Rami!

**Comment by conglei** [comment]
My env is:
python 3.9
pydantic version: 1.8.2
graphegene version: 2.1.9

For this env, the issues occurs all the time:

```
line 137, in convert_pydantic_field
    f = Field(resolver=get_attr_resolver(field.name), **field_kwargs)
TypeError: __init__() missing 1 required positional argument: 'type'
```
I think it is because for `graphene.types.field.Field`, it needs `type`..

**Comment by conglei** [comment]
Ah.. I think I need to upgrade graphene version..

**Comment by conglei** [comment]
I wonder if we can test the version of graphene here to make it backward compatible. Currently, upgrading the version of `graphene` may take tons of work.. 

If I commented out the line

```python
    if "type_" not in field_kwargs and "type" in field_kwargs:
        field_kwargs["type_"] = field_kwargs.pop("type")
```

It will work.

**Pull request merged**
